-- creation_db.sql
CREATE DATABASE IF NOT EXISTS PERMIS_DB;

USE PERMIS_DB;

CREATE TABLE IF NOT EXISTS AUTO_ECOLE (
    NOMAUTOECOLE VARCHAR(100) PRIMARY KEY,
    DEPARTEMENT VARCHAR(50) NOT NULL,
    IFU VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CANDIDAT (
    ID_CAND INT AUTO_INCREMENT PRIMARY KEY,
    NPI VARCHAR(50) NOT NULL UNIQUE,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    DATNAIS DATE NOT NULL,
    VILLE VARCHAR(100) NOT NULL,
    SEXE ENUM('M', 'F') NOT NULL,
    CATEGORIEPERMIS ENUM('A', 'B', 'C', 'D') NOT NULL,
    NOMAUTOECOLE VARCHAR(100) NOT NULL,
    FOREIGN KEY (NOMAUTOECOLE) REFERENCES AUTO_ECOLE(NOMAUTOECOLE)
);